//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLUESEA_MUSIC_CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM
    {
        public long Id { get; set; }
        [System.ComponentModel.DisplayName("Tên bài hát")]
        public string SongName { get; set; }
        [System.ComponentModel.DisplayName("Tên bài hát không dấu")]
        public string SongNameNonAccent { get; set; }
        [System.ComponentModel.DisplayName("Tên ca sĩ")]
        public string SingerName { get; set; }
        [System.ComponentModel.DisplayName("Tên ca sĩ không dấu")]
        public string SingerNameNonAccent { get; set; }
        [System.ComponentModel.DisplayName("Tên nhạc sĩ")]
        public string MusicianName { get; set; }
        [System.ComponentModel.DisplayName("Tên nhạc sĩ không dấu")]
        public string MusicianNameNonAccent { get; set; }
        [System.ComponentModel.DisplayName("Số hợp đồng QLQ")]
        public string QLQContractNo { get; set; }
        [System.ComponentModel.DisplayName("Số phụ lục hợp đồng QLQ")]
        public string QLQContractAppendixNo { get; set; }
        [System.ComponentModel.DisplayName("Số thứ tự hợp đồng QLQ")]
        public string QLQContractIndex { get; set; }
        [System.ComponentModel.DisplayName("Ngày hết hạn hợp đồng QLQ")]
        public string QLQContractOutOfDate { get; set; }
        [System.ComponentModel.DisplayName("Số hợp đồng QLG")]
        public string QLGContractNo { get; set; }
        [System.ComponentModel.DisplayName("Số phụ lục hợp đồng QLG")]
        public string QLGContractAppendixNo { get; set; }
        [System.ComponentModel.DisplayName("Số thứ tự hợp đồng QLG")]
        public string QLGContractIndex { get; set; }
        [System.ComponentModel.DisplayName("Ngày hết hạn hợp đồng QLG")]
        public string QLGContractOutOfDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        [System.ComponentModel.DisplayName("Trạng thái hợp đồng")]
        public string ContractStatus { get; set; }
        public Nullable<int> Status { get; set; }
        [System.ComponentModel.DisplayName("Ghi chú")]
        public string Note { get; set; }
        public string ExclusiveSong { get; set; }
        public string DigitalMusicRights { get; set; }
    }
}
