//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBHDTCHUNG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Serial { get; set; }
        public string Code { get; set; }
        public string Model { get; set; }
        public string MadeIn { get; set; }
        public Nullable<System.DateTime> Exportdate { get; set; }
        public Nullable<System.DateTime> Arisingdate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Limited { get; set; }
        public string Category { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public string Createby { get; set; }
        public Nullable<System.DateTime> Importdate { get; set; }
    }
}
