//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBHDTCHUNG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductActive
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> Activedate { get; set; }
        public string Activeby { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> Buydate { get; set; }
        public string CarBrandname { get; set; }
        public string InstallationAgentAddress { get; set; }
        public string ProductCode { get; set; }
    }
}
