//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBHDTCHUNG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempBrandname
    {
        public string Id { get; set; }
        public string ShowName { get; set; }
        public string TempSearch { get; set; }
        public string TempActive { get; set; }
        public string TempWarranti { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Activeweb { get; set; }
    }
}
